### PR TITLE
issue #10

### PR DESCRIPTION
**Pull request by jz709u**
make titles optional
-made placeholder text = “Add Title”
-removed existing note string to be initially blank

### CODE REVIEW

**Comment by atmoio** [comment]
This looks good. Can you explain the storyboard changes though? It seems there's a lot of 0.5 changes in positions and size for views.

**Comment by jz709u** [comment]
I have no idea why it changed all those all I did was change the text in the placeholder...

**Comment by jz709u** [comment]
let me look into it...

**Comment by jz709u** [comment]
Looks like it's because of this:
http://stackoverflow.com/questions/26598115/interface-builder-degrades-storyboards-resizes-and-repositions-views-in-small-i

I'm working on a mackbook 2016 with retina screen 2304 x 1440

**Comment by atmoio** [comment]
Interesting. Ok I guess we'll just have to deal with it. I'll go ahead and merge this.

**Pull request merged**
