### PR TITLE
Sync timer

### PR DESCRIPTION
**Pull request by jz709u**
sync timer added to the AppDelegate

### CODE REVIEW

**Comment by atmoio** [comment]
Thanks for this pull. AppDelegates should remain lightweight though. I think it would be best to create a SyncController class and do the sync logic in there. Then initialize the SyncController singleton from the AppDelegate.

**Comment by jz709u** [comment]
done

**Comment by atmoio** [comment]
@jz709u what's your email address? Wanted to send you a message.

**Comment by jz709u** [comment]
jz709u@gmail.com

**Pull request merged**
